import { useEffect, useMemo, useState } from "react";
import { ChevronDown, ChevronRight, FileCode2, Folder, FolderOpen, X } from "lucide-react";
import { useLocation, useNavigate } from "react-router-dom";

const explorerTree = [
  ["home", "/", [["intro.jsx", "intro"], ["capabilities.jsx", "capabilities"], ["highlights.jsx", "highlights"]]], ["about", "/about", [["profile.jsx", "profile"], ["focus.jsx", "focus"], ["toolkit.jsx", "toolkit"]]], ["skills", "/skills", [["distribution.jsx", "distribution"], ["capabilities.jsx", "capabilities"], ["technology.jsx", "technology"], ["mapping.jsx", "mapping"]]], ["projects", "/projects", [["archive.jsx", "archive"]]], ["experience", "/experience", [["internship.jsx", "internship"], ["ibm-datathon.jsx", "ibm-datathon"]]], ["creative", "/creative", [["story.jsx", "story"], ["gallery.jsx", "gallery"], ["process.jsx", "process"]]], ["blog", "/blog", [["featured.jsx", "featured"], ["articles.jsx", "articles"]]], ["contact", "/contact", [["message.jsx", "message"], ["availability.jsx", "availability"]]],
].map(([name, path, files]) => ({ name, path, files }));

function Sidebar({ isOpen, onClose }) {
  const location = useLocation(), navigate = useNavigate();
  const current = useMemo(() => explorerTree.find((folder) => folder.path === location.pathname) || explorerTree[0], [location.pathname]);
  const [expanded, setExpanded] = useState(new Set([current.name])); const [active, setActive] = useState(location.hash.slice(1) || current.files[0][1]);
  useEffect(() => { setExpanded((old) => new Set([...old, current.name])); setActive(location.hash.slice(1) || current.files[0][1]); }, [current, location.hash]);
  useEffect(() => { const root = document.querySelector(".main-content"), nodes = current.files.map(([, id]) => document.getElementById(id)).filter(Boolean); if (!root || !nodes.length) return; const observer = new IntersectionObserver((entries) => { const hit = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (hit) { setActive(hit.target.id); window.history.replaceState(null, "", `${current.path}#${hit.target.id}`); } }, { root, rootMargin: "-10% 0px -65%", threshold: [.05, .2] }); nodes.forEach((node) => observer.observe(node)); return () => observer.disconnect(); }, [current]);
  const go = (folder, id = folder.files[0][1]) => { setExpanded((old) => new Set([...old, folder.name])); setActive(id); navigate({ pathname: folder.path, hash: `#${id}` }); setTimeout(() => document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }), 60); onClose?.(); };
  const toggle = (name) => setExpanded((old) => { const next = new Set(old); next.has(name) ? next.delete(name) : next.add(name); return next; });
  return <aside className={`sidebar explorer ${isOpen ? "explorer-open" : "explorer-closed"}`} aria-label="Portfolio explorer"><div className="sidebar-header"><span className="sidebar-label">EXPLORER</span><button className="explorer-close" onClick={onClose} aria-label="Close explorer"><X size={16} /></button></div><nav className="explorer-tree"><div className="explorer-root"><ChevronDown size={14} /><FolderOpen size={14} />AKSHATA-PORTFOLIO</div><div className="explorer-src"><div className="explorer-root"><ChevronDown size={14} /><FolderOpen size={14} />src</div>{explorerTree.map((folder) => { const open = expanded.has(folder.name), isCurrent = folder.path === current.path; return <div className="explorer-folder" key={folder.name}><div className={`explorer-folder-row ${isCurrent ? "current" : ""}`}><button onClick={() => toggle(folder.name)} aria-label={`Toggle ${folder.name}`} aria-expanded={open}>{open ? <ChevronDown size={14} /> : <ChevronRight size={14} />}</button><button onClick={() => go(folder)}>{open ? <FolderOpen size={14} /> : <Folder size={14} />}<span>{folder.name}</span></button></div>{open && <div className="explorer-files">{folder.files.map(([name, id]) => <button key={id} onClick={() => go(folder, id)} className={isCurrent && active === id ? "active" : ""} aria-current={isCurrent && active === id ? "page" : undefined}><FileCode2 size={13} />{name}</button>)}</div>}</div>; })}</div><button className="explorer-readme" onClick={() => go(explorerTree[0])}><FileCode2 size={13} />README.md</button></nav><div className="sidebar-bottom"><div className="sidebar-folder">› portfolio</div><div className="sidebar-meta">8 sections · 2026</div><div className="explorer-availability"><i />Available for opportunities</div></div></aside>;
}
export default Sidebar;
